default:
  @just --list

# Creates a new blog post.
post BLOG_POST_NAME:
    hugo new content content/blog/{{BLOG_POST_NAME}}.md

# Serve the generated webpage.
serve:
  hugo server

# Remove the output generated by hugo.
clean:
  rm -rf ./public
